<?php

/**
 * @file
 * Contains study.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;

/**
 * Implements hook_help().
 */
function study_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the study module.
    case 'help.page.study':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('D8 India study group') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function study_cron() {
  $blocks =  \Drupal::entityTypeManager()
    ->getStorage('block_content')
    ->loadByProperties(array('type' => 'stock_exchange_rate_card'));
  foreach ($blocks AS $block) {
    $symbol = $block->field_symbol->value;

    $stockData = _make_API_call($symbol);
    $block->field_last_price = $stockData->LastPrice;
    $block->field_change = $stockData->Change;
    $block->save();
  }
}

/**
 * Helper function to fetch Last Price and Change
 * http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol=BAC&callback=myFunction
 */
function _make_API_call($stock) {
  $url = "http://dev.markitondemand.com/MODApis/Api/v2/Quote/json?symbol=" . $stock;

  $client = new GuzzleHttp\Client();
  $response = $client->get($url);
  return json_decode((string) $response->getBody());
}

/**
 * Implements hook_entity_insert().
 */
function study_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityTypeId() !== 'user') {
    return;
  }

  /** @var QueueFactory $queue_factory */
  $queue_factory = \Drupal::service('queue');
  /** @var QueueInterface $queue */
  $queue = $queue_factory->get('cron_user_mail');
  $item = new \stdClass();
  $item->uid = $entity->id();
  $queue->createItem($item);
}

/**
 * Implements hook_page_attachments().
 */
function study_page_attachments(array &$attachments) {
  // Attach the library on every page request.
  $attachments['#attached']['library'][] = 'study/drupal.study';
}

/**
 * Implements hook_theme().
 */
function study_theme($existing, $type, $theme, $path) {
  return array(
    'contact' => array(
      'render element' => 'elements',
      'file' => 'contact.page.inc',
      'template' => 'contact',
    )
  );
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function study_node_update(EntityInterface $entity) {
  \Drupal::logger('Node Updates')
    ->notice('Node with title %title of type %type has been updated', [
      '%title' => $entity->label(),
      '%type' => $entity->bundle(),
    ]);
}
